### ISSUE TITLE
Inquiries about "Rain rendering for evaluating and improving robustness to bad weather"

### ISSUE THREAD

**Issue by wangjiyuan9** [cv-rits/weather-particle-simulator#7] opened 2023-05-24 14:04 UTC
Dear author,
Hello! I am following your article "Rain rendering for evaluating and improving robustness to bad weather". This is really great work!
I noticed that you mentioned the nuscenes-augment dataset（PBR+GAN） used for downstream task in rainy conditions in your paper. Would it be possible to share it with me? I would like to test my models on this dataset. Thank you!
Also, in the paper, you mentioned using curriculum learning to complete the optimization. What are the details of this part? How was the curriculum set up, and how was the training scheduler set up? 
Finally, you stated that "we found that training from scratch with heavy rain or random rainfall rates" fails to converge, but from my observation, both train on heavy rain or on the hybrid method can converge. I don't understand how you arrived at the conclusion in the paper.
Thank you for your time and help. Looking forward to your reply!

**Comment by rdecharette** [comment] 2023-05-30 08:35
Wrong repo and duplicate of: https://github.com/astra-vision/rain-rendering/issues/25

Please avoid double-posting, the same day I received the request twice in Github and twice in emails, a bit too much :wink:

**Closed as completed by rdecharette** 2023-05-30 08:35 UTC
